# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e54834c164b99e297a070b5ec5d2979b142e9d65958aa17e73d927e90af0dd8b3a08b20497e76979155471785c437146ee81bca25af75d5c1eec86592ae3c8ec

test:
  secret_key_base: aef6c56cbb3ce91d9458fb837ccb171e1da21563b30fc5463afcb04c2bfcfab3b5cb239f99142f1b5c3e85a1326470f89278a55774623b11d0abf22fd3482730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
